apiVersion: v1
kind: Service
metadata:
  name: mywebsite
  labels:
    app: mywebsite
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: mywebsite
